using System;

namespace DoenaSoft.SqlServerDatabaseMeta;

/// <summary>
/// Represents an object in the database covered by this library.
/// </summary>
public interface IMetaBase
{
    /// <summary>
    /// A unique Id generated by this library.
    /// </summary>
    /// <remarks>
    /// This Id does not originate from the underlying database.
    /// This Id is not persisted and a follow-up run against the same database will yield different a Id for the same object.
    /// </remarks>
    Guid MetaId { get; }

    /// <summary>
    /// Name of the object in the database covered by this library.
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Taken from sys.extended_properties 'MS_Description'.
    /// </summary>
    string Description { get; }
}